name: 'Repository Dispatch'
description: 'Create a repository dispatch event'
inputs:
  token:
    description: 'GITHUB_TOKEN or a `repo` scoped Personal Access Token (PAT)'
    default: ${{ github.token }}
  is_electron:
    description: 'Flag to use electron app workflow'
    default: 'false'
outputs:
  version:
    description: 'Application version'
  is_update:
    description: 'If version differs from latest release version'
runs:
  using: 'node20'
  main: 'dist/action.cjs.js'
branding:
  icon: 'target'
  color: 'gray-dark'
