name: 'AppImage Creator Action'
description: 'Action to assist on AppImage creation'
inputs:
  token:
    description: 'GITHUB_TOKEN or a `repo` scoped Personal Access Token (PAT)'
  electron:
    description: 'Flag to use electron app workflow'
outputs:
  version:
    description: 'Application version'
  is_update:
    description: 'If version differs from latest release version'
runs:
  using: 'composite'
  steps:
    - run: mkdir ${GITHUB_WORKSPACE}/output
      shell: bash
    - run: |
        docker run --rm --user root --device /dev/fuse --privileged \
          -e IS_ELECTRON="true" -e GITHUB_REPOSITORY="${env.GITHUB_REPOSITORY}" -e GITHUB_TOKEN="${{ inputs.token }}" -e OUTPUT_PATH=${GITHUB_ACTION_PATH}/output \
          -v ${GITHUB_WORKSPACE}:/workspace -v ${GITHUB_ACTION_PATH}/output:/output ghcr.io/emiliopg91/appimage-creator-2:latest
      shell: bash
branding:
  icon: 'target'
  color: 'gray-dark'
