name: 'AppImage Creator Action'
description: 'Action to assist on AppImage creation'
inputs:
  token:
    description: 'GITHUB_TOKEN or a `repo` scoped Personal Access Token (PAT)'
    default: ${{ github.token }}
  is_electron:
    description: 'Flag to use electron app workflow'
    default: 'false'
outputs:
  version:
    description: 'Application version'
  is_update:
    description: 'If version differs from latest release version'
runs:
  using: 'composite'
  steps:
    - run: sudo apt-get update
      shell: bash
    - run: sudo apt-get install -y jq libfuse2 zsync
      shell: bash
    - run: chmod +x $GITHUB_ACTION_PATH/resources/appimagetool
      shell: bash
    - uses: actions/setup-node@v4
      with:
        node-version: '20'
    - run: node dist/action.cjs.js
      shell: bash
branding:
  icon: 'target'
  color: 'gray-dark'
