name: Auto Release Patch

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y jq libfuse2

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Install project
        run: pnpm i

      - name: Clear dist folder if exists
        run: |
          if [ -d "dist" ]; then
            rm -R dist
          fi

      - name: Build bundles
        run: |
          pnpm build

      - name: Testing
        run: |
          pnpm test

      - name: Perform release
        run: |
          node dist/release.cjs.js
        env:
          GITHUB_TOKEN: ${{ secrets.GH_ACTION_PAT }}
